# Configuration for Cloudflare Pages

# Cloudflare Pages configuration for production

# Set the compatibility date
compatibility_date = "2023-12-01"

# Build settings
[build]
  command = "npm run build"
output_dir = "dist"

# Routes for API endpoints
[[routes]]
pattern = "/api/channel-thumbnails"
function = "api/channel-thumbnails"

# Static assets (should come last)
[[routes]]
pattern = "/*"
static = "dist"

# Redirects and rewrites - comment this out since we're using Functions for API
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-api-backend.example.com/api/:splat"
#   status = 200
#   force = true
#   headers = {X-From = "Cloudflare-Pages"}

# Static asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML and page data
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 