# Configuration for Cloudflare Pages

[build]
  command = "npm run build:force"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

# Redirects and rewrites - comment this out since we're using Functions for API
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-api-backend.example.com/api/:splat"
#   status = 200
#   force = true
#   headers = {X-From = "Cloudflare-Pages"}

# Static asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML and page data
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 