# Cloudflare Pages Configuration
name = "aiman-portfolio"
compatibility_date = "2024-05-17"
compatibility_flags = []

# Build configuration
[build]
command = "npm run build"

# Routes configuration for functions
[[routes]]
pattern = "/api/channel-thumbnails"
function = "channel-thumbnails"

[[routes]]
pattern = "/api/thumbnails/download"
script = "server.js"

[[routes]]
pattern = "/api/thumbnails/collage"
script = "server.js"

[[routes]]
pattern = "/api/*"
script = "server.js"

# Static assets
[[routes]]
pattern = "/*"
static = "dist"

[env.production]
API_URL = "https://api.aimansalim.com"

[env.staging]
API_URL = "https://staging-api.aimansalim.com" 