# Cloudflare Pages Configuration
name = "aiman-portfolio"
compatibility_date = "2024-05-17"
compatibility_flags = []

# Build configuration
[build]
command = "npm run build"
output_dir = "dist"

[site]
bucket = "dist"

[env.production]
API_URL = "https://api.aimansalim.com"

[env.staging]
API_URL = "https://staging-api.aimansalim.com" 